server:
  port: 8080

spring:
  datasource:
    username: root
    password: Mysql1234.
    url: jdbc:mysql://localhost:3306/mybatis
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.zhbit.pojo